### ISSUE TITLE
modules.import_module error during serving  

### ISSUE THREAD

**Issue by sivakhno** [aws/sagemaker-containers#214]
We extend pytorch docker container 
`FROM 520713654638.dkr.ecr.$REGION.amazonaws.com/sagemaker-pytorch:1.0.0-$ARCH-py3 `
with custom fast.ai branch.

The training works well, but during serving I get persistent error message (I tried few things like increasing instance size. but unsuccessfully). 
The traceback from CloudWatch:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_pytorch_container/serving.py", line 103, in main
user_module = modules.import_module(serving_env.module_dir, serving_env.module_name)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 244, in import_module
install(_env.code_dir)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 110, in install
_process.check_error(shlex.split(cmd), _errors.InstallModuleError, cwd=path, capture_error=capture_error)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_process.py", line 48, in check_error
raise error_class(return_code=return_code, cmd=' '.join(cmd), output=stderr)
```

My question is how I can make debugging message more specific, i.e. shouldn't `raise error_class(return_code=return_code, cmd=' '.join(cmd), output=stderr)` print the cmd line so that identity of install string is known?

Any suggestions would be most appreciated!

**Comment by ivanmartinvalle** [comment]
I'm running into this as well with `ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3`

```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_sklearn_container/serving.py", line 99, in main
user_module = modules.import_module(serving_env.module_dir, serving_env.module_name)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 251, in import_module
six.reraise(_errors.ImportModuleError, _errors.ImportModuleError(e), sys.exc_info()[2])
File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_modules.py", line 246, in import_module
module = importlib.import_module(name)
File "/usr/lib/python3.5/importlib/__init__.py", line 117, in import_module
if name.startswith('.'):
```

**Comment by ivanmartinvalle** [comment]
Figured it out. This was completely unintuitive. I originally had this working with the following pseudocode:

```python
model = SKLearn()
model.fit(wait=True)
model.deploy(wait=True)
```

I had since refactored to split the fit and deploy into separate steps:
```python
# first.py
model = SKLearn()
model.fit(wait=False)

# second.py, ran much later
latest_training_job = get_latest_training_job()
estimator = Estimator.attach(latest_training_job)
estimator.deploy(wait=False)
```

There is some magic somewhere in the first path that sets some critical environment variables, mainly:
```sh
SAGEMAKER_CONTAINER_LOG_LEVEL=20
SAGEMAKER_ENABLE_CLOUDWATCH_METRICS=false
SAGEMAKER_PROGRAM=train.py
SAGEMAKER_REGION=us-east-1
SAGEMAKER_SUBMIT_DIRECTORY=s3://bucket/source.tar.gz
```

I only discovered this by running Sagemaker in [local mode](https://sagemaker.readthedocs.io/en/stable/overview.html#local-mode), noticed it worked there, wondering how it could have gotten the code if I never uploaded it to the container, and finally tracking down the successful model and the failed model and comparing their configuration.

The solution for me was this:
```python
estimator.deploy(env={
  'SAGEMAKER_PROGRAM': 'train.py',
  # the rest of the environment variables from above
})
```

**Comment by icywang86rui** [comment]
@ivanmartinvalle 
Glad that you are unblocked. Feel free to reopen the issue if you have any further questions.

**Comment by sivakhno** [comment]
@icywang86rui - unfortunately setting env variables didn't really help in my case - I still get the same error. In my case training works well, but serving part get stuck. Can we reopen the issue?

**Comment by ajaykarpur** [comment]
Hi @sivakhno, sorry about the long delay. Were you able to resolve your error? If not, can you provide more details about what you've tried so far?

We really appreciate the feedback, @ivanmartinvalle. I'll add some tasks in our backlog to improve the specificity of the debugging messages and the overall clarity and user experience of the serving process.

**Comment by warmlogic** [comment]
Hi @ajaykarpur, I'm currently dealing with this same issue using a [sklearn container](https://github.com/aws/sagemaker-scikit-learn-container). The same issue seems to have been posted about [here](https://stackoverflow.com/questions/58050712/problem-deploying-the-best-estimator-gotten-with-sagemaker-estimator-estimator) (not my post).

Here's the stacktrace for the error I'm getting:

```
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/miniconda3/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
    addr)
  File "/miniconda3/lib/python3.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 119, in main
    user_module_transformer = import_module(serving_env.module_name, serving_env.module_dir)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/serving.py", line 97, in import_module
    user_module = importlib.import_module(module_name)
  File "/miniconda3/lib/python3.7/importlib/__init__.py", line 118, in import_module
    if name.startswith('.'):
```

and then the actual error:

```AttributeError: 'NoneType' object has no attribute 'startswith'```

I can see in the SageMaker console Models section that my model was trained with the image `246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:0.20.0-cpu-py3` (I don't manually specify this when I train). When I trained this sklearn preprocessor (it's a `Pipeline` that I `fit` like in [this example](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk/scikit_learn_inference_pipeline)), I used the `entry_point` and `source_dir` arguments. I see in the training logs that the environment variable for the module directory gets set correctly: `SM_MODULE_DIR=s3://mybucket/mymodelname/source/sourcedir.tar.gz` (which is where the contents of `source_dir` get tar.gz'd and saved to). I see in my model's environment variables (via the SageMaker console) that the `SAGEMAKER_SUBMIT_DIRECTORY` environment variable is properly set to the `sourcedir.tar.gz` path mentioned above. I'm able to batch transform with the trained preprocessor, so that implies that everything is correct with the source directory or the serialized model file.

Given the error, it seems like the root of the issue is that [`module_name`](https://github.com/aws/sagemaker-scikit-learn-container/blob/ae81aeeec81a615c4059a1b1db6d2e2730743ac1/src/sagemaker_sklearn_container/serving.py#L97) is `None` (note that I linked to an older version of `serving.py` because the code line numbers from the error stacktrace in my cloudwatch logs match this older version). [Here](https://github.com/aws/sagemaker-containers/blob/a84f48a1ede4aa7dd96dbd050d27ac540d8ce59b/src/sagemaker_containers/_env.py#L329) is where `module_name` gets set, and the fallback is `None`. I can see in my model in the SageMaker console that the environment variable `SAGEMAKER_PROGRAM` is already properly set to the name of my `.py` file (stored in `sourcedir.tar.gz`), so I'm not sure why this wouldn't be found. It also seems like this variable could get set by a [parameter](https://github.com/aws/sagemaker-containers/blob/a84f48a1ede4aa7dd96dbd050d27ac540d8ce59b/src/sagemaker_containers/_params.py#L19) but I'm not sure where I would set that. I wonder if some process behind deploying the endpoint can't find the `sourcedir.tar.gz` file? I can confirm this file does exist and that SageMaker can access it from an IAM perspective. I tried removing this file temporarily and got the same error `AttributeError: 'NoneType' object has no attribute 'startswith'`, which potentially lends evidence to that hypothesis.

Manually setting the `SAGEMAKER_PROGRAM` env variable when I run `create_model` like was mentioned earlier in this issue didn't work for me. When I do this, the logs tell me that it couldn't find the module and then was able to successfully install it over and over for about 13 minutes and eventually the endpoint deployment fails without any more information. It also seems to be using `sagemaker_containers` as opposed to `sagemaker_sklearn_container`, but I'm not sure what impact that has.

I see that the `module_dir` referenced in the error should be set to the `SAGEMAKER_SUBMIT_DIRECTORY ` environment variable that I mentioned above (see [here](https://github.com/aws/sagemaker-containers/blob/a84f48a1ede4aa7dd96dbd050d27ac540d8ce59b/src/sagemaker_containers/_env.py#L330)), though I have no way to confirm this is actually the case.

What's especially weird is that the behavior is inconsistent. Most of the time it fails, but I have had it successfully deploy with the exact same code...

Please let me know if I can provide any more info. My team and I would love to get this solved!
