### ISSUE TITLE
Issue: Failed to run: ['docker-compose', '-f', ...

### ISSUE THREAD

**Issue by nectario** [aws/sagemaker-containers#274]
When I try to run in local mode I get:
```
tmpsqcmqlg5_algo-1-5rcld_1 exited with code 1
Aborting on container exit...
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 161, in train
    _stream_output(process)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 677, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Development/Projects/DeepTradingAI/deeptradingmodels/DeepTradingEstimator.py", line 7, in <module>
    estimator.fit()
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\estimator.py", line 494, in fit
    self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_config)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\estimator.py", line 1066, in start_new
    estimator.sagemaker_session.train(**train_args)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\session.py", line 590, in train
    self.sagemaker_client.create_training_job(**train_request)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\local_session.py", line 102, in create_training_job
    training_job.start(InputDataConfig, OutputDataConfig, hyperparameters, TrainingJobName)
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\entities.py", line 96, in start
    input_data_config, output_data_config, hyperparameters, job_name
  File "C:\Program Files\Python37\lib\site-packages\sagemaker\local\image.py", line 166, in train
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', 'C:\\Users\\NEKTAR~1\\AppData\\Local\\Temp\\tmpsqcmqlg5\\docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1
```

**Comment by chuyang-deng** [comment]
Hi @nectario, could you specify which framework and version you are using?

And also please note this repo `sagemaker-containers` is deprecated and if you are using it to build your own containers, we recommend using [sagemaker-inference-toolkit](https://github.com/aws/sagemaker-inference-toolkit) and [sagemaker-training-toolkit](https://github.com/aws/sagemaker-training-toolkit)
